[package]
name = "donnees"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"


[lib]
name = "donnees"
crate-type = ["cdylib", "lib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.42"
